### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by Ta2Ta2** [mrjeanp/Arcane-SEO#8]
Hi,

Doing clean install for the latest version by adding the add-on through the backend while it doesn't show any errors, however, the plugin is nowhere found as functional. no setting folder, no components...etc.

please advise

**Comment by mrjeanp** [comment]
@Ta2Ta2 i will take a look

**Comment by Ta2Ta2** [comment]
Oh man.. I forget I even opened this ticket. 

I did another fresh install now and all is well. 

Merry Christmas
