### ISSUE TITLE
Multi language 

### ISSUE THREAD

**Issue by MH-Zarkhani** [mrjeanp/Arcane-SEO#9]
tnx for great seo plugin octobercms
please implement multi language support like this 
![seo](https://user-images.githubusercontent.com/17814936/68068621-ebbef880-fd6b-11e9-8665-7c1190455073.png)
If it does, it will be much better

**Comment by Ladylain** [comment]
Hello, i've made a pull request to fix this. For now, only Page title and Page description are translatable. But i'll try later to add OG fields,etc...

Hope it could help

**Comment by Ladylain** [comment]
Hi, 

i've updated my pull request with improvements for OG translation. 

I think the next step would be to let user choose which field could be translated, cause at the moment, i had to add an extra option on the config Yaml file to determine if the field needs to be translatable or not. 

best,
